# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: "j1"
        steps:
        - task: Maven@3
          inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'clean install'

  - stage: Test
    displayName: Test
    jobs:
      - job: "j2"
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              mavenVersionOption: 'Default'
              mavenOptions: '-Xmx3072m'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              goals: 'clean verify'

  - stage: ArtifactAndPackage
    jobs:
          - job: 'j3'
            pool: server
            steps:
            - task: ServiceNow-DevOps-Server-Artifact-Registration@1
              inputs:
                connectedServiceName: 'empsunildevops9-TestDevOpsProject-ServiceNow DevOps Service Connection'
                artifactRegistrationPayload: |
                  {
                     "artifacts": [
                        {
                           "name": "DevOps-ADO-Maven-CI_artifact_",
                           "version": "1.$(build.buildId)",
                           "semanticVersion": "1.$(build.buildId).0",
                           "repositoryName": "test-snow-devops-ado"
                        },
                        {
                           "name": "DevOps-ADO-Maven-CI_artifact-2_",
                           "version": "1.$(build.buildId)",
                           "semanticVersion": "1.$(build.buildId).0",
                           "repositoryName": "test-snow-devops-ado"
                        }
                     ],
                     "pipelineName": "$(system.teamProject)/$(build.definitionName)",
                     "taskExecutionNumber": "$(build.buildId)",
                     "stageName": "$(System.StageDisplayName)/$(system.jobDisplayName)",
                     "branchName": "$(build.sourceBranchName)"
                  }
                artifactToolIdExists: false
            - task: ServiceNow-DevOps-Server-Package-Registration@1
              inputs:
                connectedServiceName: 'empsunildevops9-TestDevOpsProject-ServiceNow DevOps Service Connection'
                packageRegistrationPayload: |
                  {
                      "name": "pkg$(build.buildId)",
                      "artifacts": [
                      {
                          "name": "DevOps-ADO-Maven-CI_artifact_",
                          "repositoryName": "test-snow-devops-ado",
                          "version": "1.$(build.buildId)",
                          "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                          "taskExecutionNumber":"$(build.buildId)",
                          "stageName":"$(System.StageName)/$(system.jobDisplayName)",
                          "branchName":"$(build.sourceBranchName)"
                      }],
                      "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                      "taskExecutionNumber":"$(build.buildId)",
                      "stageName":"$(System.StageName)/$(system.jobDisplayName)",
                      "branchName":"$(build.sourceBranchName)"
                  }
                artifactToolIdExists: false
  - stage: Deploy
    displayName: Deploy
    jobs:
      - job: j4
        pool: server
        steps:
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'empsunildevops9-TestDevOpsProject-ServiceNow DevOps Service Connection'
            changeRequestDetails: |
              {
                "attributes": {
                  "short_description": "Test desc",
                  "priority": "1",
                  "start_date": "2022-01-05 08:00:00",
                  "justification": "test just",
                  "description": "test descri",
                  "cab_required": true,
                  "work_notes": "test work"
                },
                "setCloseCode": false
              }

